# Generated by Django 2.0.1 on 2018-01-25 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subway_app', '0002_auto_20180124_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='subway',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
