# Generated by Django 2.0.1 on 2018-01-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway_app', '0003_subway_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
