# Generated by Django 2.0.1 on 2018-01-25 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway_app', '0004_delete_subway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('TrainNo', models.IntegerField()),
                ('TrainSttus', models.IntegerField()),
                ('StationNm', models.CharField(max_length=10)),
                ('StatnTnm', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
